---
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: gravitee-mongodb
spec:
  members: 2
  type: ReplicaSet
  version: "4.2.6"
  statefulSet:
    spec:
      terminationGracePeriodSeconds: 10
      volumeClaimTemplates:
      - metadata:
          name: data-volume
        spec:  
          resources:
            requests:
              storage: 5Gi
      - metadata:
          name: logs-volume
        spec:
          resources:
            requests:
              storage: 5Gi
  security:
    authentication:
      modes: ["SCRAM"]
  users:
    - name: my-user
      db: gravitee-apim
      passwordSecretRef: # a reference to the secret that will be used to generate the user's password
        name: my-user-password
      roles:
        - name: clusterAdmin
          db: gravitee-apim
        - name: userAdminAnyDatabase
          db: gravitee-apim
        - name: readWrite
          db: gravitee-apim
      scramCredentialsSecretName: my-user
    - name: my-user-am
      db: gravitee-am
      passwordSecretRef: # a reference to the secret that will be used to generate the user's password
        name: my-user-am-password
      roles:
        - name: clusterAdmin
          db: gravitee-am
        - name: userAdminAnyDatabase
          db: gravitee-am
        - name: readWrite
          db: gravitee-am
      scramCredentialsSecretName: my-user-am
  additionalMongodConfig:
    storage.wiredTiger.engineConfig.journalCompressor: zlib

# the user credentials will be generated from this secret
# once the credentials are generated, this secret is no longer required
---
apiVersion: v1
kind: Secret
metadata:
  name: my-user-password
type: Opaque
stringData:
  password: password
---
apiVersion: v1
kind: Secret
metadata:
  name: my-user-am-password
type: Opaque
stringData:
  password: password
